name: Build and Push to GHCR

on:
  pull_request:
    types:
      - closed
    branches:
      - main  # Trigger only when a PR is merged to main
  workflow_dispatch:  # Allow manual execution

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run build script with GHCR Tag
        run: |
          GHCR_IMAGE="ghcr.io/${{ github.repository_owner }}/aws-s3-signed-upload"
          chmod +x ./build.sh
          ./build.sh "$GHCR_IMAGE"
          echo "GHCR_IMAGE=$GHCR_IMAGE" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image to GHCR
        run: |
          docker push ${{ env.GHCR_IMAGE }}
