name: Build and Push to Docker Hub

on:
  pull_request:
    types:
      - closed
    branches:
      - main  # Trigger only when a PR is merged to main
  workflow_dispatch:  # Allow manual execution

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run build script
        run: |
          chmod +x ./build.sh
          ./build.sh

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract image name from build script (Optional)
        id: extract_image
        run: |
          IMAGE_NAME=$(grep -oP 'docker build -t \K[^ ]+' build.sh | head -1)
          echo "Extracted Image Name: $IMAGE_NAME"
          echo "image=$IMAGE_NAME" >> $GITHUB_ENV

      - name: Push Docker image
        run: |
          docker push ${{ env.image }}
