name: Build and Push to GHCR (Multi-Arch + Versioning)

on:
  push:
    tags:
      - 'v*'  # Trigger only on version tags (e.g., v1.0.0)
  pull_request:
    types:
      - closed
    branches:
      - main  # Trigger only when a PR is merged to main
  workflow_dispatch:  # Allow manual execution

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version tag (if available)
        id: version
        run: |
          if [[ "${{ github.ref }}" == refs/tags/v* ]]; then
            VERSION="${GITHUB_REF#refs/tags/}"
          else
            VERSION="latest"
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "GHCR_IMAGE=ghcr.io/${{ github.repository_owner }}/aws-s3-signed-upload:$VERSION" >> $GITHUB_ENV

      - name: Build and push multi-architecture image
        run: |
          chmod +x ./build.sh
          docker buildx create --use

          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --push \
            -t ${{ env.GHCR_IMAGE }} \
            -t ghcr.io/${{ github.repository_owner }}/aws-s3-signed-upload:latest \
            -f build/Dockerfile .
